theme: jekyll-theme-primer
title: Project Description
description: Spotify Playlist Recommender Proect
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
